### ISSUE TITLE
`progress_estimated()` was deprecated 

### ISSUE THREAD

**Issue by misizsembes** [e-kotov/wikimapR#1]
<img width="636" alt="Screenshot 2023-05-08 at 20 13 27" src="https://user-images.githubusercontent.com/40657082/236887575-67373c89-4c15-42f9-bc89-3e23cc3f90f7.png">

**Comment by e-kotov** [comment]
Thank you for reporting this, I will look into it soon and provide a fix.

**Comment by e-kotov** [comment]
@misizsembes This should now be fixed, however, during my testing I have also found out that Wikimapia has deprecated the key API function I relied upon, for more details see issue https://github.com/e-kotov/wikimapR/issues/2 . So the package may not work for now. I will try to fix that soon.

UPDATE: Using 'example' API key does not work, however everything seems to be working with your a private API key.
